version: "3"
services:
  # docker-compose -f docker-compose.yml up --detach --build  ## for recreating th

  api:
    container_name: ${app}-api
    image: 'zelejs/allin-web:jdk11'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api:/webapps
    environment:
      TZ: "Asia/Shanghai"
      GREENFIELD: 'run'

  mysqlserver:
    container_name: ${app}-mysql
    image: 'daocloud.io/library/mysql:5.7'
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf


